title: Karthik's blog
email: Karthik.bhata7@gmail.com
description: >- # 
  NETWORKING AND SECURITY ENTHUSIAST
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: karthikbhata
github_username:  karthikbhata97

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
